version: '3.7'

volumes:
  orderer.postal.com:
  peer-nairobi.org1.postal.com:
  peer-atlanta.org1.postal.com:
  peer-singapore.org2.postal.com:

networks:
  postal:
    name: postal_network

services:
  # Certificate Authority for Org1
  ca_org1:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    ports:
      - "7054:7054"
      - "17054:17054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.postal.com/ca/:/etc/hyperledger/fabric-ca-server
    container_name: ca_org1
    networks:
      - postal

  # Certificate Authority for Org2
  ca_org2:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:18054
    ports:
      - "8054:8054"
      - "18054:18054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.postal.com/ca/:/etc/hyperledger/fabric-ca-server
    container_name: ca_org2
    networks:
      - postal

  # Orderer Node
  orderer.postal.com:
    container_name: orderer.postal.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/postal.com/orderers/orderer.postal.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/postal.com/orderers/orderer.postal.com/tls/:/var/hyperledger/orderer/tls
      - orderer.postal.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - postal

  # Peer Nairobi - Org1
  peer-nairobi.org1.postal.com:
    container_name: peer-nairobi.org1.postal.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=postal_network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer-nairobi.org1.postal.com
      - CORE_PEER_ADDRESS=peer-nairobi.org1.postal.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer-nairobi.org1.postal.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer-atlanta.org1.postal.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer-nairobi.org1.postal.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org1.postal.com/peers/peer-nairobi.org1.postal.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.postal.com/peers/peer-nairobi.org1.postal.com/tls:/etc/hyperledger/fabric/tls
      - peer-nairobi.org1.postal.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - postal

  # Peer Atlanta - Org1
  peer-atlanta.org1.postal.com:
    container_name: peer-atlanta.org1.postal.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=postal_network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer-atlanta.org1.postal.com
      - CORE_PEER_ADDRESS=peer-atlanta.org1.postal.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer-atlanta.org1.postal.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer-nairobi.org1.postal.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer-atlanta.org1.postal.com:8051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org1.postal.com/peers/peer-atlanta.org1.postal.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org1.postal.com/peers/peer-atlanta.org1.postal.com/tls:/etc/hyperledger/fabric/tls
      - peer-atlanta.org1.postal.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 8051:8051
    networks:
      - postal

  # Peer Singapore - Org2
  peer-singapore.org2.postal.com:
    container_name: peer-singapore.org2.postal.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=postal_network
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer-singapore.org2.postal.com
      - CORE_PEER_ADDRESS=peer-singapore.org2.postal.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer-singapore.org2.postal.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer-singapore.org2.postal.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org2.postal.com/peers/peer-singapore.org2.postal.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.postal.com/peers/peer-singapore.org2.postal.com/tls:/etc/hyperledger/fabric/tls
      - peer-singapore.org2.postal.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
    networks:
      - postal

  # CLI Container for administrative tasks
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer-nairobi.org1.postal.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.postal.com/peers/peer-nairobi.org1.postal.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.postal.com/peers/peer-nairobi.org1.postal.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.postal.com/peers/peer-nairobi.org1.postal.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.postal.com/users/Admin@org1.postal.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock
      - ../chaincode:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.postal.com
      - peer-nairobi.org1.postal.com
      - peer-atlanta.org1.postal.com
      - peer-singapore.org2.postal.com
    networks:
      - postal
